export const mockPatients = [
  {
    id: "P001",
    unitStayId: "UST001",
    name: "John Smith",
    email: "john@example.com",
    password: "password123",
    dob: "1985-03-15",
    gender: "Male",
    phone: "555-0101",
    address: "123 Main St, City, State",
    aadhaar: "1234-5678-9012",
    medicalHistory: "Hypertension, Diabetes Type 2",
    currentMedications: "Lisinopril, Metformin",
    diagnosis: "Essential Hypertension with Diabetes",
    symptoms: "Chest pain, shortness of breath, fatigue",
    allergies: "Penicillin, Aspirin",
    doctorAssigned: "Dr. Rajesh Sharma",
    testResults: "ECG: Abnormal - ST elevation noted. Blood glucose: 240 mg/dL",
    prescriptions: [
      { id: "PR001", medicine: "Lisinopril 10mg", dosage: "Once daily", duration: "30 days" },
      { id: "PR002", medicine: "Metformin 500mg", dosage: "Twice daily", duration: "30 days" },
      { id: "PR003", medicine: "Aspirin 75mg", dosage: "Once daily", duration: "30 days" },
    ],
    doctorNotes:
      "Patient requires regular monitoring. ECG shows signs of cardiac stress. Recommend dietary changes and regular exercise.",
    reports: [
      {
        id: "R001",
        type: "Blood Test",
        date: "2025-01-10",
        doctor: "Dr. Sharma",
        result: "Abnormal",
        file: "blood_test_jan.pdf",
        details: "Glucose elevated, Cholesterol high",
      },
      {
        id: "R002",
        type: "ECG",
        date: "2025-01-05",
        doctor: "Dr. Sharma",
        result: "Abnormal",
        file: "ecg_jan.pdf",
        details: "ST elevation in leads II, III, aVF",
      },
    ],
    admissionDate: "2025-01-05",
    dischargeDate: null,
    wardRoom: "ICU-A",
    treatmentCost: 15000,
    insuranceProvider: "National Health Insurance",
    paymentStatus: "pending",
    totalBill: 15000,
  },
  {
    id: "P002",
    unitStayId: "UST002",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    password: "password123",
    dob: "1990-07-22",
    gender: "Female",
    phone: "555-0102",
    address: "456 Oak Ave, City, State",
    aadhaar: "9876-5432-1098",
    medicalHistory: "Asthma, Allergic Rhinitis",
    currentMedications: "Albuterol inhaler, Cetrizine",
    diagnosis: "Acute Asthma Exacerbation",
    symptoms: "Shortness of breath, wheezing, chest tightness",
    allergies: "Sulfonamides, Latex",
    doctorAssigned: "Dr. Priya Patel",
    testResults: "Chest X-ray: Clear, Spirometry: FEV1 60%",
    prescriptions: [
      { id: "PR004", medicine: "Albuterol Inhaler", dosage: "As needed", duration: "Ongoing" },
      { id: "PR005", medicine: "Fluticasone Propionate", dosage: "Twice daily", duration: "30 days" },
    ],
    doctorNotes:
      "Patient presents with acute asthma exacerbation. Started on corticosteroid therapy. Good response to treatment observed.",
    reports: [
      {
        id: "R003",
        type: "Chest X-Ray",
        date: "2025-01-12",
        doctor: "Dr. Patel",
        result: "Clear",
        file: "xray_jan.pdf",
        details: "No infiltrates or consolidation",
      },
    ],
    admissionDate: "2025-01-12",
    dischargeDate: "2025-01-15",
    wardRoom: "Ward-B-201",
    treatmentCost: 8000,
    insuranceProvider: "Private Health Plus",
    paymentStatus: "paid",
    totalBill: 8000,
  },
  {
    id: "P003",
    unitStayId: "UST003",
    name: "Michael Brown",
    email: "michael@example.com",
    password: "password123",
    dob: "1975-11-30",
    gender: "Male",
    phone: "555-0103",
    address: "789 Pine Rd, City, State",
    aadhaar: "5555-6666-7777",
    medicalHistory: "Broken Leg, Osteoarthritis",
    currentMedications: "Ibuprofen, Physical Therapy",
    diagnosis: "Tibia and Fibula Fracture",
    symptoms: "Severe pain, swelling, inability to bear weight",
    allergies: "NSAIDs (alternative: acetaminophen)",
    doctorAssigned: "Dr. Arun Desai",
    testResults: "X-ray: Complete fracture of tibia and fibula with displacement",
    prescriptions: [
      { id: "PR006", medicine: "Acetaminophen 500mg", dosage: "Three times daily", duration: "14 days" },
      { id: "PR007", medicine: "Morphine 10mg", dosage: "Every 4 hours as needed", duration: "7 days" },
      { id: "PR008", medicine: "Cephalexin 500mg", dosage: "Twice daily", duration: "10 days" },
    ],
    doctorNotes:
      "Patient underwent surgical fixation with internal plates. Post-operative recovery progressing well. PT to begin after 1 week.",
    reports: [
      {
        id: "R004",
        type: "X-Ray (Tibia)",
        date: "2025-01-08",
        doctor: "Dr. Desai",
        result: "Fracture detected",
        file: "xray_leg_jan.pdf",
        details: "Comminuted fracture with displacement",
      },
      {
        id: "R005",
        type: "CT Scan",
        date: "2025-01-02",
        doctor: "Dr. Desai",
        result: "Normal",
        file: "ct_jan.pdf",
        details: "No other injuries detected",
      },
    ],
    admissionDate: "2025-01-02",
    dischargeDate: null,
    wardRoom: "Orthopedic Ward-A-105",
    treatmentCost: 35000,
    insuranceProvider: "Employee Benefits Cover",
    paymentStatus: "pending",
    totalBill: 35000,
  },
]

export const mockDoctors = [
  {
    id: "D001",
    name: "Dr. Rajesh Sharma",
    email: "sharma@hospital.com",
    password: "password123",
    role: "cardiologist",
    specialization: "Cardiology",
  },
  {
    id: "D002",
    name: "Dr. Priya Patel",
    email: "patel@hospital.com",
    password: "password123",
    role: "orthopaedic",
    specialization: "Orthopaedics",
  },
  {
    id: "D003",
    name: "Dr. Arun Desai",
    email: "desai@hospital.com",
    password: "password123",
    role: "general_physician",
    specialization: "General Medicine",
  },
]

export const mockStaff = [
  {
    id: "S001",
    name: "Rahul Kumar",
    email: "rahul@hospital.com",
    password: "password123",
    role: "front_desk",
  },
  {
    id: "S002",
    name: "Priya Singh",
    email: "priya@hospital.com",
    password: "password123",
    role: "billing_desk",
  },
]

export const getAllUsers = () => [...mockPatients, ...mockDoctors, ...mockStaff]
